### ISSUE TITLE
Script doesn't create collections of users, reports

### ISSUE THREAD

**Issue by dev-nicelee** [fireship-io/fireship-quizapp-data#27]
I've used the script to create collections by following instructions on README

It has created quizzes and topics without any data loss, but it seems like it doesn't create users, reports collections..

Is this intended and should be created manually?🤔

**Comment by muthpeter** [comment]
It will be generated dinamically later by the app.

**Comment by helderlj** [comment]
I feel like this should be fixed somewhere.
